SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS leadparceiro;

DROP TABLE IF EXISTS checkout_asaas;
DROP TABLE IF EXISTS eventolote;
DROP TABLE IF EXISTS evento;

DROP TABLE IF EXISTS pagvenda;
DROP TABLE IF EXISTS itvenda;
DROP TABLE IF EXISTS venda;

DROP TABLE IF EXISTS itcarrinho;
DROP TABLE IF EXISTS carrinho;

DROP TABLE IF EXISTS produto;
DROP TABLE IF EXISTS categoria;

DROP TABLE IF EXISTS usuario;
DROP TABLE IF EXISTS clisenha;
DROP TABLE IF EXISTS cliente;

DROP TABLE IF EXISTS lojahorario;
DROP TABLE IF EXISTS loja;
DROP TABLE IF EXISTS organizacao;

DROP TABLE IF EXISTS bairro;
DROP TABLE IF EXISTS cidade;
DROP TABLE IF EXISTS estado;
DROP TABLE IF EXISTS pais;

SET FOREIGN_KEY_CHECKS = 1;
