ALTER TABLE usuario MODIFY COLUMN dscargo ENUM(
  'SUPERADMIN', 'ADMIN', 'GERENTE', 'MANAGER', 'CAIXA', 'CASHIER', 'TOTEM',
  'BARMAN', 'GARCOM', 'WAITER', 'PORTEIRO', 'TICKETMAN'
) NOT NULL DEFAULT 'BARMAN';

UPDATE usuario SET dscargo = 'MANAGER' WHERE dscargo = 'GERENTE';
UPDATE usuario SET dscargo = 'WAITER' WHERE dscargo = 'GARCOM';
UPDATE usuario SET dscargo = 'TICKETMAN' WHERE dscargo = 'PORTEIRO';
UPDATE usuario SET dscargo = 'CASHIER' WHERE dscargo = 'CAIXA';

ALTER TABLE usuario MODIFY COLUMN dscargo ENUM(
  'SUPERADMIN', 'ADMIN', 'MANAGER', 'CASHIER', 'TOTEM',
  'BARMAN', 'WAITER', 'TICKETMAN'
) NOT NULL DEFAULT 'BARMAN';
