CREATE TABLE IF NOT EXISTS lojacontabancaria (
  lojacontabancaria_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  organizacao_id BIGINT NOT NULL,
  loja_id BIGINT NOT NULL,
  codigobanco VARCHAR(10) NOT NULL,
  nmbanco VARCHAR(100) NULL,
  agencia VARCHAR(20) NOT NULL,
  nrconta VARCHAR(30) NOT NULL,
  digitoconta VARCHAR(5) NULL,
  tipoconta VARCHAR(20) NOT NULL DEFAULT 'CORRENTE',
  nmtitular VARCHAR(150) NOT NULL,
  cpfcnpjtitular VARCHAR(20) NOT NULL,
  chavepix VARCHAR(150) NULL,
  tipochavepix VARCHAR(20) NULL,
  status VARCHAR(15) NOT NULL DEFAULT 'ATIVA',
  dtcriacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  dtultatu DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_lojacontabancaria_loja (loja_id),
  CONSTRAINT fk_lojacontabancaria_organizacao FOREIGN KEY (organizacao_id) REFERENCES organizacao (organizacao_id),
  CONSTRAINT fk_lojacontabancaria_loja FOREIGN KEY (loja_id) REFERENCES loja (loja_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS repassefinanceiro (
  repassefinanceiro_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  organizacao_id BIGINT NOT NULL,
  loja_id BIGINT NOT NULL,
  venda_id BIGINT NOT NULL,
  checkout_asaas_id BIGINT NULL,
  vrbruto DECIMAL(10,2) NOT NULL,
  vrtaxaclubbar DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  vrrepasse DECIMAL(10,2) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
  dtprevista DATE NULL,
  dtpagamento DATETIME NULL,
  idtransferencia VARCHAR(100) NULL,
  urlcomprovante VARCHAR(500) NULL,
  observacao TEXT NULL,
  codigobanco VARCHAR(10) NULL,
  agencia VARCHAR(20) NULL,
  nrconta VARCHAR(30) NULL,
  digitoconta VARCHAR(5) NULL,
  tipoconta VARCHAR(20) NULL,
  nmtitular VARCHAR(150) NULL,
  cpfcnpjtitular VARCHAR(20) NULL,
  dtcriacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  dtultatu DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_repassefinanceiro_venda (venda_id),
  INDEX idx_repassefinanceiro_status_data (status, dtcriacao),
  INDEX idx_repassefinanceiro_loja (loja_id),
  CONSTRAINT fk_repassefinanceiro_organizacao FOREIGN KEY (organizacao_id) REFERENCES organizacao (organizacao_id),
  CONSTRAINT fk_repassefinanceiro_loja FOREIGN KEY (loja_id) REFERENCES loja (loja_id),
  CONSTRAINT fk_repassefinanceiro_venda FOREIGN KEY (venda_id) REFERENCES venda (venda_id),
  CONSTRAINT fk_repassefinanceiro_checkout FOREIGN KEY (checkout_asaas_id) REFERENCES checkout_asaas (checkout_asaas_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
