CREATE TABLE IF NOT EXISTS operador (
  operador_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nmoperador VARCHAR(200) NOT NULL,
  emailoperador VARCHAR(200) NOT NULL,
  senhahashoperador VARCHAR(255) NOT NULL,
  perfil VARCHAR(30) NOT NULL DEFAULT 'ADMIN',
  sitoperador VARCHAR(15) NOT NULL DEFAULT 'ATIVO',
  dtcriacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  dtultatu DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_operador_email (emailoperador)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
